# Custom machine for Raspberry Pi 4 (LSMY)
# Extends the upstream raspberrypi4 machine

require conf/machine/raspberrypi4.conf

# Map custom machine to upstream Raspberry Pi 4 BSP
KERNEL_MACHINE = "raspberrypi4"

# Inherit raspberrypi4 kernel & BSP overrides
MACHINEOVERRIDES .= ":raspberrypi4"

# Enable common peripherals
ENABLE_UART = "1"
ENABLE_I2C  = "1"
ENABLE_I2C1 = "1"

# Enable camera support
# ENABLE_CAMERA = "1"
# VIDEO_CAMERA = "1"

# Camera-specific configurations
KERNEL_MODULE_AUTOLOAD:append = " ov5647 bcm2835_unicam bcm2835-isp"

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
    overlays/ov5647.dtbo \
"

RPI_EXTRA_CONFIG:append = "\
dtoverlay=ov5647 \n\
camera_auto_detect=1 \n\
media-controller=1 \n\
gpu_mem=128 \n\
"