# Custom machine for Raspberry Pi 4 (LSMY)
# Extends the upstream raspberrypi4 machine

require conf/machine/raspberrypi4.conf

# Map custom machine to upstream Raspberry Pi 4 BSP
KERNEL_MACHINE = "raspberrypi4"

# Inherit raspberrypi4 kernel & BSP overrides
MACHINEOVERRIDES .= ":raspberrypi4"

# Enable common peripherals
ENABLE_UART = "1"
ENABLE_I2C  = "1"

# Camera configuration
# Enable camera support
VIDEO_CAMERA = "1"

# Camera-specific configurations
KERNEL_MODULE_AUTOLOAD:append = " bcm2835-v4l2 ov5647"

RPI_EXTRA_CONFIG:append = " \n \
dtoverlay=ov5647 \n \
gpu_mem=128 \n \
    "