# Custom machine for Raspberry Pi 4 (LSMY)
# Extends the upstream raspberrypi4 machine

require conf/machine/raspberrypi4.conf

# Map custom machine to upstream Raspberry Pi 4 BSP
KERNEL_MACHINE = "raspberrypi4"

# Inherit raspberrypi4 kernel & BSP overrides
MACHINEOVERRIDES .= ":raspberrypi4"

# Enable common peripherals
ENABLE_UART = "1"
ENABLE_I2C  = "1"

# Camera-specific configurations
KERNEL_MODULE_AUTOLOAD:append = " ov5647 bcm2835_unicam"
KERNEL_DEVICETREE:append = " overlays/ov5647.dtbo"

OSTREE_KERNEL_ARGS:append = " bcm2835_unicam.video_nr=0 rpivid_v4l2.video_nr=10"

RPI_EXTRA_CONFIG:append = "\
dtoverlay=ov5647 \n\
gpu_mem=128 \n\
dtoverlay=rpivid-v4l2,disable \n\
"