# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-lsmy"
BBFILE_PATTERN_meta-lsmy = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-lsmy = "6"

LAYERDEPENDS_meta-lsmy = "core"
LAYERSERIES_COMPAT_meta-lsmy = "scarthgap"

FORTRAN:forcevariable = ",fortran"

PACKAGECONFIG:append:pn-gcc = " fortran"
PACKAGECONFIG:append:pn-gcc-cross-aarch64 = " fortran"
PACKAGECONFIG:append:pn-gcc-runtime = " fortran"
PACKAGECONFIG:append:pn-gcc-crosssdk = " fortran"

PREFERRED_VERSION_tensorflow-lite = "2.9.1"
