# lsmy-distro.conf
# Custom distribution configuration for LSMY project

require conf/distro/poky.conf

DISTRO = "lsmy-distro"
DISTRO_NAME = "LSMY Lab Monitoring Distribution"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "scarthgap"

# Use systemd as init manager
DISTRO_FEATURES:append = " systemd usrmerge"
DISTRO_FEATURES:remove = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

# Use IPK as package format
PACKAGE_CLASSES = "package_ipk"

# Remove SPDX
INHERIT:remove = "create-spdx"

# Enable package index
# INHERIT:append = " package-index"

# Enable extra users
INHERIT:append = " extrausers"

EXTRA_USERS_PARAMS = "\
    useradd -p '' admin; \
    useradd -p '' user; \
    usermod -aG sudo admin; \
"

# Enable package signing
INHERIT:append = " sign_ipk"

GPG_PATH = "/home/ironman/.gnupg"
GPG_NAME = "thanhkoten3@gmail.com"
GPG_PASSPHRASE = "25092004"

# Use X11 as graphics backend
# DISTRO_FEATURES:append = " x11"

# Use wayland as graphics backend
DISTRO_FEATURES:remove = "x11"
DISTRO_FEATURES:append = " wayland pam"

# Use TensorFlow Lite
DISTRO_FEATURES:append = " tensorflow-lite"
PREFERRED_VERSION_tensorflow-lite = "2.9.1"

# Enable fortran support
FORTRAN:forcevariable = ",fortran"

PACKAGECONFIG:append:pn-gcc = " fortran"
PACKAGECONFIG:append:pn-gcc-cross-aarch64 = " fortran"
PACKAGECONFIG:append:pn-gcc-runtime = " fortran"
PACKAGECONFIG:append:pn-gcc-crosssdk = " fortran"
